build:
  image: node:latest
  environment:
    - PRIMARY_SAUCE_USERNAME=$$PRIMARY_SAUCE_USERNAME
    - PRIMARY_SAUCE_ACCESS_KEY=$$PRIMARY_SAUCE_ACCESS_KEY
    - SECONDARY_SAUCE_USERNAME=$$SECONDARY_SAUCE_USERNAME
    - SECONDARY_SAUCE_ACCESS_KEY=$$SECONDARY_SAUCE_ACCESS_KEY
  commands:
    - export BUILD_NUMBER=$DRONE_BUILD_NUMBER
    - npm install --quiet
    - npm install --quiet -g karma-cli
    - npm test

publish:
  coverage:
    token: $$GITHUB_TOKEN
    include: jackspirou/clientjs/coverage/lcov.info
    when:
      branch: master
